Fix CI error detection

diff --git a/.github/workflows/ci_suite.yml b/.github/workflows/ci_suite.yml
--- a/.github/workflows/ci_suite.yml
+++ b/.github/workflows/ci_suite.yml
@@ -78,12 +78,9 @@ jobs:
       - name: Check for warnings or errors
         id: check-errors
         run: |
-          if grep -q "error" compile.log; then
-            echo "::error ::Compilation failed with errors."
-            exit 1
-          elif grep -q "warning" compile.log; then
-            echo "::warning ::Compilation failed with warnings."
-            exit 1
+          if grep -q " 0 errors, 0 warnings" compile.log; then
+            echo "Compilation succeeded."
           else
-            echo "Compilation succeeded without critical errors."
+            echo "::error:: Compilation failed."
+            exit 1
           fi
